/** The one place that explains how the portal works. Keep answers short and true to what the system does. */
export interface Faq { q: string; a: string[] }
export interface FaqSection { id: string; title: string; items: Faq[] }

export const FAQ: FaqSection[] = [
  { id: 'start', title: 'Getting started', items: [
    { q: 'What is the difference between the CEO and an accountant?', a: ['The CEO has every permission and approves loans. An accountant can do what the CEO has ticked for them in Staff & Permissions; by default that is: view and register customers and complete their details, create loans (which wait for approval), record repayments and transactions, request top-ups, and view and export reports.', 'The CEO can change anyone\'s permissions at any time; changes apply immediately.'] },
    { q: 'How does approval work?', a: ['When an accountant creates a loan (one at a time or through the Monthly upload) it is saved as Pending. Nothing is paid out and no repayments can be recorded until it is approved.', 'The CEO opens the pending loan, can edit it (amount, duration, dates, rates), then approves or rejects it. A CEO\'s own loans are approved straight away.'] },
    { q: 'What can an accountant do without the CEO?', a: ['Accountants can view and download everything (reports, statements, schedules, the customer register and the loan book), register and update customers, create loans, record repayments and ledger entries, and request top-ups.', 'Sensitive changes need the CEO: correcting a payment, reversing a transaction, changing a running loan and deleting a customer. The accountant presses Request on that item, the request appears under Approvals, and nothing changes until the CEO approves it.'] },
    { q: 'Where do the dashboard numbers come from?', a: ['Everything is calculated from the ledger (the list of every disbursement and payment). Nothing is typed in by hand, so the figures cannot drift from the transactions.'] },
  ] },
  { id: 'customers', title: 'Customers', items: [
    { q: 'How do I register a customer?', a: ['Customers → Add customer. Choose the type of worker first. Government workers need an IPPIS number and a ministry; non-government workers enter the organisation they work for. Then fill in personal details, phone, email, address, state, NIN and BVN (11 digits each) and next of kin.', 'An IPPIS number, NIN, BVN, phone number or email can belong to only one customer.'] },
    { q: 'What is the customer ID?', a: ['It is the client number from the old loan book with the PTC prefix: client 640 is PTC-000640. New customers continue after the highest number. The ID cannot be changed.'] },
    { q: 'What does "Incomplete profile" mean?', a: ['Customers imported from the old sheet only have a name, IPPIS and ministry. The profile lists what is missing (phone, address, NIN, BVN, date of birth, marital status, next of kin…). Click Complete profile and fill in what you have; you can save a little at a time. The dashboard shows how many profiles are still incomplete, and Customers can be filtered by Profile.'] },
    { q: 'How does the CEO import the old customer sheet?', a: ['Customers → Import from Excel. You see what will happen first and nothing is saved until you confirm. Client numbers become customer IDs; rows with an IPPIS number are government workers, rows without are non-government. Duplicate or missing client numbers get a new number and are listed. Running the import again is safe.'] },
    { q: 'Can I delete a customer?', a: ['Only if they have no loans or transactions. Otherwise set their status to Inactive or Suspended so the financial history stays on record.'] },
  ] },
  { id: 'loans', title: 'Loans', items: [
    { q: 'How is a loan calculated?', a: ['Principal = the amount requested (plus any balance brought forward on a top-up). Interest is a flat rate on that principal: monthly interest = principal × 5%, total interest = monthly interest × number of months. Gross loan (the total repayment) = principal + total interest. EMI = gross loan ÷ number of months (to the kobo; the last installment absorbs the difference).', 'Example: ₦500,000 over 12 months → monthly interest ₦25,000, total interest ₦300,000, gross loan ₦800,000, EMI ₦66,666.67 × 12.', 'Interest never changes after the loan starts, whatever is paid.'] },
    { q: 'How do I bring in loans that are already running (opening balances)?', a: ['Monthly upload → Opening balances. Upload a sheet with Client ID, Clients Name, IPPIS NO, Ministry, Loan, Repayment to date and a Balance column (the date can be in the header, e.g. "Balance as at 30 Sep, 2026", or chosen on the page). A sheet with only a Balance uses the balance as the loan.', 'The Loan becomes that customer\'s running loan (no further interest is added), the Repayment to date is recorded as already paid, and the balance is what is left. Repayments can then be recorded against it and a later TOP UP has a loan to liquidate. No cash is paid out; the ledger shows non-cash entries. Loan − Repayment is the balance used (a different Balance cell gives a warning). A customer who has repaid more than the loan, or owes nothing, is skipped. Customers who already have an open loan are skipped, people not in the portal are added with their Client ID. Accountants\' uploads wait for the CEO to approve.'] },
    { q: 'What is the Application Fee?', a: ['A separate 4% fee on the amount requested (₦20,000 on ₦500,000). It is shown on its own and is never part of the principal, the interest, the gross loan, the EMI or the balance the customer repays.'] },
    { q: 'Why can I not create a second loan for a customer?', a: ['A customer can have only one open loan (pending or running). If they already have one, do a top-up instead. The limit can be changed in Settings.'] },
    { q: 'When are repayments due?', a: ['The first installment falls in the month after the loan starts, whatever day it started. The payment window opens on the 25th and each installment is due on the 30th (28 or 29 in February). Loans set up with a specific first payment date keep it.'] },
    { q: 'Who can edit a loan?', a: ['Pending loans can be edited by anyone with permission to edit loans. Running loans can be edited only by the CEO, with a reason: the schedule is rebuilt and the repayments already recorded are applied again. Every change is in the audit log.'] },
    { q: 'Where are completed loans?', a: ['Fully repaid loans move to Completed loans, so the Loans list only shows pending, running and overdue ones. A customer\'s own page still shows their full history.'] },
  ] },
  { id: 'payments', title: 'Repayments and payments', items: [
    { q: 'How do I record a payment?', a: ['On the loan page: Record repayment (any amount), or Mark paid next to an installment (pre-filled with what is owed, but you can change the amount). Choose the method and reference, and attach proof such as a debit or credit alert.'] },
    { q: 'What can I upload as proof?', a: ['PDF, PNG/JPG, Word or Excel files, up to 4 MB each and 5 per payment. You see a preview before saving; later, click the payment to see the proof, preview it and download it.'] },
    { q: 'What if the customer pays a little too much?', a: ['A payment may exceed the balance by up to ₦1,000 (a Settings value). ₦30,000 sent for ₦29,999.82 clears the loan and the small excess is held as credit.'] },
    { q: 'I entered a payment wrongly. How do I fix it?', a: ['The CEO opens the payment and chooses Edit repayment, with a reason. The old entry is reversed and a corrected one is posted; both stay visible and are audited. Anyone with permission can also reverse a payment.'] },
    { q: 'Why do paid installments move down?', a: ['So the next payment due is always at the top of the schedule. Paid installments sit below a "Paid" line.'] },
  ] },
  { id: 'topups', title: 'Top-ups', items: [
    { q: 'How is a top-up calculated?', a: ['(a) loan taken, (b) revised tenor = the months the old loan was actually used, (c) revised cost = (a) × (1 + rate × (b)), (d) repaid to date, (e) outstanding = (c) − (d), (f) liquidation fee = 5% of (e), (g) amount due = (e) + (f).', '(g) is carried into the new loan as its balance brought forward. The new loan is priced on (g) plus the new money. You can change the months used in the top-up request, and the fee in Settings → Top-up rules.'] },
    { q: 'What happens to the old loan?', a: ['It is closed by a non-cash entry once the new loan is approved; nothing is overwritten. Both loans stay in the history.'] },
  ] },
  { id: 'monthly', title: 'Monthly upload', items: [
    { q: 'How do I change many customers or loans at once?', a: ['Monthly upload → download the Register (Excel). It has every customer once. The loan figures come first: Clients ID (PTC-######), name, IPPIS, ministry, tenor, payment date, balance B/Fwd, loan amount, application fee, principal, interest, gross loan, EMI, start and end dates, status and Loan ID. The customer\'s profile details are at the end: customer status, worker type, phone, email, address, state, gender, marital status, date of birth, NIN, BVN and next of kin name and phone.', 'Change whatever needs changing in Excel, save, and upload the same file. You see exactly what will change, row by row, before anything is saved.'] },
    { q: 'How do I complete an incomplete profile from Excel?', a: ['The last column, "Profile (missing details)", lists what is still missing for each customer. Fill in those cells (phone, email, address, state, gender, marital status, date of birth, NIN, BVN, next of kin name and phone, worker type) and upload. When nothing is missing the profile shows as complete.', 'You can also change the Customer status (Active, Inactive, Suspended, Blacklisted) in the sheet.'] },
    { q: 'How are the rows understood?', a: ['Each row is matched to a customer by IPPIS NO first. If the row has no IPPIS (or that IPPIS is not in the portal yet), the Clients ID is used (641 or PTC-000641 both work). A row with only an IPPIS is enough. If the two point to different people, the IPPIS decides and a warning is shown. A changed IPPIS is accepted if nobody else has it.', 'Customer details that differ are updated; blank cells never erase anything.', 'A row with a Loan ID is that customer\'s current loan: changed figures update it (the CEO for running loans).', 'A row without a Loan ID but with loan figures is a new loan: NEW or RENEWAL, or TOP UP which liquidates the running loan.', 'Rows that are unchanged are left alone.'] },
    { q: 'What if I leave Application Fee, Principal, Interest, Gross Loan or EMI blank?', a: ['Leave them blank: the portal calculates them. Application fee = 4% of the loan amount, principal = balance B/Fwd + loan amount, interest = principal × 5% × tenor, gross loan = principal + interest, EMI = gross loan ÷ tenor.', 'If an EMI is written in the sheet it is respected (total = EMI × tenor) and the interest follows from it.'] },
    { q: 'Does an accountant\'s upload need approval?', a: ['New loans are created as Pending for the CEO to edit and approve. Customer detail updates go through if the accountant may update customers. Changing a running loan needs the CEO.'] },
    { q: 'What if the customer is not in the portal yet?', a: ['Leave Clients ID empty. A row with an IPPIS number that is not in the portal is added as a government customer; a row with no IPPIS is added as a non-government customer and the MINISTRY cell becomes their organisation. They get the next PTC number and an incomplete profile to fill in later. A client number that is not found is refused, as it is probably a typo.'] },
    { q: 'What is the empty template for?', a: ['The same columns, with example rows (a top-up, a new loan and a new customer with no client number). Fill the white columns and leave the calculated ones empty.'] },
  ] },
  { id: 'downloads', title: 'Statements, reports and downloads', items: [
    { q: 'How do I download a statement?', a: ['Open a customer or loan → Generate statement. Choose dates if you like, then PDF, Excel (with a monthly breakdown) or CSV. A customer statement shows the current loan; tick "Include completed loans" for the full history.', 'Tick "Include uploads (PDF only)" to add the uploaded proofs of payment to the PDF. Very large uploads may need a shorter date range.'] },
    { q: 'Can I download the repayment schedule?', a: ['Yes: on the loan page, schedule tab, as PDF, Excel or CSV.'] },
    { q: 'What reports are there?', a: ['Reports lists them all: loan book, customer register, loans, repayments, outstanding, overdue, collections, disbursements, top-ups and transactions. Loan reports cover current loans; completed loans are not included unless you choose a status.'] },
  ] },
  { id: 'admin', title: 'Staff, settings and audit', items: [
    { q: 'How do I give someone access?', a: ['Staff & Permissions → add the person and tick the permissions they need (for example Create loans, Record repayments, Export reports). Deactivate them to stop access.'] },
    { q: 'What can be changed in Settings?', a: ['Company details, whether loans need approval, allowed overpayment, how payments are allocated, early settlement, late-payment timing and the top-up rules (including the liquidation fee).'] },
    { q: 'What does the audit log record?', a: ['Who did what and when: logins, page visits, creating or changing customers, loans, payments, uploads, settings and permissions. Filter by person, role, action or date, and export it. Entries cannot be edited or deleted.'] },
  ] },
]
