/** Plain-language explanation shown at the top of every page ("About this page"). First match wins, so list specific paths first. */
export interface PageHelpEntry { key: string; match: RegExp; title: string; about: string; steps?: string[]; notes?: string[] }

export const PAGE_HELP: PageHelpEntry[] = [
  { key: 'dashboard', match: /^\/(ceo|accountant)$/, title: 'Dashboard', about: 'A live summary of the business, worked out from the ledger. Nothing here is typed in by hand.',
    steps: ['Read the cards for customers, active loans, money out (disbursed), money collected, outstanding and overdue amounts.', 'The amber banner (if shown) lists customer profiles that still lack details: click it to finish them.', 'Use the recent loans, repayments and overdue lists to jump straight to a record.'],
    notes: ['The CEO sees the full financial picture; an accountant sees what their permissions allow.'] },
  { key: 'customers-new', match: /^\/customers\/new$/, title: 'Register a customer', about: 'Creates a customer profile. The customer ID (PTC-######) is generated for you and continues after the old client numbers.',
    steps: ['Choose the type of worker first: Government (needs an IPPIS number and a ministry) or Non-government (enter the organisation).', 'Fill in personal details, contact, NIN and BVN (11 digits each), next of kin and occupation.', 'Save. Required fields are marked *.'],
    notes: ['An IPPIS number, NIN, BVN or phone number can belong to only one customer.', 'Your draft is saved in this browser while you type.'] },
  { key: 'customers-edit', match: /^\/customers\/[^/]+\/edit$/, title: 'Edit a customer', about: 'Update a customer\'s details. Profiles imported from the old loan book are incomplete: fill in what you have and come back for the rest.',
    steps: ['The amber note lists exactly which details are still missing.', 'Fill in any of them and save; you do not have to complete everything at once.'], notes: ['The customer ID cannot be changed. Every change is recorded in the audit log.'] },
  { key: 'statement', match: /^\/(customers|loans)\/[^/]+\/statement$/, title: 'Account statement', about: 'The customer\'s or loan\'s account in debit / credit form, built from the ledger: what was owed, what was paid, and the running balance.',
    steps: ['Optionally pick a date range, then Generate statement.', 'Download as PDF, Excel (with a monthly breakdown) or CSV, or print.', 'Tick "Include uploads (PDF only)" to append the uploaded proofs of payment to the PDF.'], notes: ['A client statement shows the current loan; tick "Include completed loans" for the full history.'] },
  { key: 'customer', match: /^\/customers\/[^/]+$/, title: 'Customer details', about: 'Everything about one customer: profile, financial summary, loans, repayments, transactions and activity.',
    steps: ['Use the tabs to move between sections.', '"New loan" starts a loan for this customer; if they already have one, use a top-up instead.', '"Generate statement" opens their account statement.'], notes: ['Customers with loans or transactions cannot be deleted; set their status to Inactive or Suspended instead.'] },
  { key: 'customers', match: /^\/customers$/, title: 'Customers', about: 'Everyone who borrows (or may borrow) from Protech, listed A to Z.',
    steps: ['Search by name, IPPIS number, client ID, phone or email; filter by status or by incomplete profiles.', 'Click a customer to open them. The pencil edits, the bin deletes (only if they have no financial history).', 'The CEO can import the old client sheet with "Import from Excel".'], notes: ['"Incomplete" badges show profiles that still lack details such as phone, NIN or BVN.'] },
  { key: 'loans-new', match: /^\/loans\/new$/, title: 'New loan', about: 'Creates a loan. The server calculates everything shown on the right; you only choose the customer, product, amount and terms.',
    steps: ['Pick the customer and the loan product, then the amount received, duration and start date.', 'Check the calculation: gross payment, principal, interest, total, installment and the schedule.', 'Save. As an accountant the loan goes to the CEO for approval; the CEO\'s loans are approved straight away.'],
    notes: ['A customer can have only one open loan. If they already have one, the page tells you to do a top-up instead.', 'Repayments follow the monthly cycle: the window opens on the 25th and each installment is due on the 30th (28/29 in February).'] },
  { key: 'loans-edit', match: /^\/loans\/[^/]+\/edit$/, title: 'Edit a loan', about: 'Change a loan\'s terms. Pending loans can be edited by anyone with edit rights; running loans only by the CEO.',
    steps: ['Change the amount, duration, dates or (for the CEO, on running loans) the rate and how interest is charged.', 'For a running loan, give a reason. Repayments already recorded are kept and re-applied to the new schedule.'], notes: ['The CEO can edit a loan an accountant submitted before approving it.'] },
  { key: 'loans-completed', match: /^\/loans\/completed$/, title: 'Completed loans', about: 'Loans that have been fully repaid. They are kept here as a record, away from the live loan list.', steps: ['Open any loan to see its schedule, repayments and statement.'] },
  { key: 'loan', match: /^\/loans\/[^/]+$/, title: 'Loan details', about: 'One loan: its terms, balances, repayment schedule, repayments and ledger entries.',
    steps: ['The schedule shows what is still to pay first; paid installments drop to the bottom. "Mark paid" records a payment against a month (you can change the amount).', '"Record repayment" adds any payment, with optional proof (debit/credit alert as PDF or image).', 'Click a payment to see its details and proof; the CEO can correct it. Download the schedule as PDF, Excel or CSV.', 'Settle, top up or generate a statement from the buttons at the top.'],
    notes: ['A payment may exceed the balance by up to ₦1,000 (the excess is held as credit).', 'Balances are always calculated from the ledger, never typed in.'] },
  { key: 'loans', match: /^\/loans$/, title: 'Loans', about: 'Pending, running and overdue loans. Fully repaid loans move to "Completed loans".',
    steps: ['Search or filter by status, repayment state, dates and amount; click a loan to open it.', '"New loan" creates one; "Loan book (Excel)" downloads the book with the calculation formulas.'], notes: ['The Loan book lists each customer\'s current loan once.'] },
  { key: 'monthly', match: /^\/monthly$/, title: 'Monthly upload', about: 'One place for the month\'s paperwork: upload the loans taken, and download the register of every customer with their current loan.',
    steps: ['Download the template, fill one row per customer (Clients ID, Name, IPPIS, Tenor, Payment Date, Balance B/Fwd, Bank payment, EMI, Start Date, Status NEW / TOP UP / RENEWAL).', 'Upload it. You see every row checked before anything is saved: matched customer, calculated principal, interest and EMI, and any problem.', 'Confirm. As an accountant the loans are sent to the CEO for approval; the CEO can edit each one, then approve.'],
    notes: ['Customers are matched by client number AND IPPIS; a mismatch is refused.', 'Blank calculated columns (gross payment, principal, interest, loan, EMI) are filled by the sheet formulas.', 'A TOP UP row liquidates the customer\'s running loan once approved.'] },
  { key: 'products', match: /^\/products$/, title: 'Loan products', about: 'The loan types Protech offers: interest rate, how interest is charged, bank deduction, allowed amounts, durations and repayment frequencies.',
    steps: ['Add or edit a product. Interest is a one-time flat charge by default (5% of ₦1,000,000 = ₦50,000).', 'Deactivate a product to stop new loans using it.'], notes: ['Editing a product never changes loans that already exist.'] },
  { key: 'repayments', match: /^\/repayments$/, title: 'Repayments', about: 'Every payment received, newest first.',
    steps: ['Search or filter by method, date, amount or state.', 'Click a payment to see its details and uploaded proof, add a file, edit it (CEO) or reverse it.', '"Record repayment" adds a payment to a loan.'], notes: ['Payments are never deleted. A correction reverses the old entry and posts a new one, both visible and audited.'] },
  { key: 'transactions', match: /^\/transactions$/, title: 'Transactions', about: 'The complete ledger: disbursements, repayments, top-ups, waivers, fees and reversals.',
    steps: ['Filter by type, method, customer or date.', 'Click an entry for details. Eligible entries can be reversed with a reason.'], notes: ['This is the source of truth: loan balances, statements and reports are all built from it.'] },
  { key: 'topups', match: /^\/topups$/, title: 'Top-ups', about: 'A top-up gives a customer with a running loan more money by liquidating the old loan into a new one.',
    steps: ['Start a top-up from the loan page. The liquidation is worked out as on Protech\'s sheet: revised cost for the months used, less repayments, plus the 5% liquidation fee.', 'The amount due is carried into the new loan with the new funds. The CEO approves requests from accountants.'], notes: ['The old loan is closed by a non-cash entry; nothing is overwritten.'] },
  { key: 'reports', match: /^\/reports$/, title: 'Reports', about: 'Ready-made reports built from the ledger, downloadable as Excel, PDF or CSV.',
    steps: ['Pick a report and an optional date range, then run it on screen or download it.'], notes: ['Loan reports cover current loans; use a status filter for others.', 'The customer register lists every customer once with their current loan.'] },
  { key: 'staff', match: /^\/staff(\/.*)?$/, title: 'Staff & permissions', about: 'Create staff accounts and choose exactly what each person may do.',
    steps: ['Add a staff member, then tick the permissions they need (for example Create loans, Record repayments, Export reports).', 'Deactivate someone to stop them signing in; reset a password from their page.'], notes: ['The CEO always has every permission and cannot be locked out.'] },
  { key: 'audit', match: /^\/audit$/, title: 'Audit log', about: 'A record of what happened: who did what, when, and from which page, including page visits.',
    steps: ['Filter by person, role, action type or date, or search; export the result as CSV.'], notes: ['Entries cannot be edited or deleted.'] },
  { key: 'settings', match: /^\/settings$/, title: 'Settings', about: 'Company details and the rules the system follows: approvals, repayments, late payments, top-ups and transactions.',
    steps: ['Change a section and save. Changes apply to new activity straight away.'], notes: ['Examples: whether loans need approval, the allowed overpayment, how a payment is allocated, the liquidation fee.'] },
]

export function helpFor(pathname: string): PageHelpEntry | null {
  const p = pathname.replace(/\/+$/, '') || '/'
  return PAGE_HELP.find((h) => h.match.test(p)) ?? null
}
