/** Every audit action name lives here so the log stays consistent and searchable. */
export const AUDIT = {
  PAGE_VIEW: 'PAGE_VIEW',
  STATEMENT_GENERATED: 'STATEMENT_GENERATED',
  LOGIN: 'LOGIN',
  LOGIN_FAILED: 'LOGIN_FAILED',
  LOGOUT: 'LOGOUT',
  PASSWORD_CHANGED: 'PASSWORD_CHANGED',
  PASSWORD_RESET_REQUESTED: 'PASSWORD_RESET_REQUESTED',

  CUSTOMER_CREATED: 'CUSTOMER_CREATED',
  CUSTOMERS_IMPORTED: 'CUSTOMERS_IMPORTED',
  CUSTOMER_UPDATED: 'CUSTOMER_UPDATED',
  CUSTOMER_STATUS_CHANGED: 'CUSTOMER_STATUS_CHANGED',
  CUSTOMER_DELETED: 'CUSTOMER_DELETED',

  STAFF_CREATED: 'STAFF_CREATED',
  STAFF_UPDATED: 'STAFF_UPDATED',
  STAFF_ACTIVATED: 'STAFF_ACTIVATED',
  STAFF_DEACTIVATED: 'STAFF_DEACTIVATED',
  STAFF_PERMISSION_CHANGED: 'STAFF_PERMISSION_CHANGED',
  STAFF_PASSWORD_RESET: 'STAFF_PASSWORD_RESET',
  STAFF_ROLE_CHANGED: 'STAFF_ROLE_CHANGED',
  STAFF_DELETED: 'STAFF_DELETED',

  PRODUCT_CREATED: 'PRODUCT_CREATED',
  PRODUCT_UPDATED: 'PRODUCT_UPDATED',
  PRODUCT_DELETED: 'PRODUCT_DELETED',

  LOAN_CREATED: 'LOAN_CREATED',
  LOAN_UPDATED: 'LOAN_UPDATED',
  LOAN_APPROVED: 'LOAN_APPROVED',
  LOAN_REJECTED: 'LOAN_REJECTED',
  LOAN_CANCELLED: 'LOAN_CANCELLED',
  LOAN_DISBURSED: 'LOAN_DISBURSED',
  LOAN_DEFAULTED: 'LOAN_DEFAULTED',
  LOAN_STATUS_CHANGED: 'LOAN_STATUS_CHANGED',

  REPAYMENT_RECORDED: 'REPAYMENT_RECORDED',
  INSTALLMENT_MARKED_PAID: 'INSTALLMENT_MARKED_PAID',
  REPAYMENT_EDITED: 'REPAYMENT_EDITED',
  ATTACHMENT_ADDED: 'ATTACHMENT_ADDED',
  LOAN_SETTLED_EARLY: 'LOAN_SETTLED_EARLY',
  TRANSACTION_CREATED: 'TRANSACTION_CREATED',
  TRANSACTION_REVERSED: 'TRANSACTION_REVERSED',

  TOPUP_REQUESTED: 'TOPUP_REQUESTED',
  TOPUP_APPROVED: 'TOPUP_APPROVED',
  TOPUP_REJECTED: 'TOPUP_REJECTED',
  TOPUP_CANCELLED: 'TOPUP_CANCELLED',

  SETTINGS_CHANGED: 'SETTINGS_CHANGED',
  REPORT_EXPORTED: 'REPORT_EXPORTED',
} as const;
export type AuditAction = (typeof AUDIT)[keyof typeof AUDIT];
