/** Every audit action name lives here so the log stays consistent and searchable. */
export const AUDIT = {
  LOGIN: 'LOGIN',
  LOGIN_FAILED: 'LOGIN_FAILED',
  LOGOUT: 'LOGOUT',
  PASSWORD_CHANGED: 'PASSWORD_CHANGED',
  PASSWORD_RESET_REQUESTED: 'PASSWORD_RESET_REQUESTED',

  CUSTOMER_CREATED: 'CUSTOMER_CREATED',
  CUSTOMER_UPDATED: 'CUSTOMER_UPDATED',
  CUSTOMER_STATUS_CHANGED: 'CUSTOMER_STATUS_CHANGED',
  CUSTOMER_DELETED: 'CUSTOMER_DELETED',

  STAFF_CREATED: 'STAFF_CREATED',
  STAFF_UPDATED: 'STAFF_UPDATED',
  STAFF_ACTIVATED: 'STAFF_ACTIVATED',
  STAFF_DEACTIVATED: 'STAFF_DEACTIVATED',
  STAFF_PERMISSION_CHANGED: 'STAFF_PERMISSION_CHANGED',
  STAFF_PASSWORD_RESET: 'STAFF_PASSWORD_RESET',
  STAFF_ROLE_CHANGED: 'STAFF_ROLE_CHANGED',
  STAFF_DELETED: 'STAFF_DELETED',
} as const;
export type AuditAction = (typeof AUDIT)[keyof typeof AUDIT];
